config/routes.rb
Rails.application.routes.draw do
  resources :person_infos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person_experience.rb
class PersonExperience < ApplicationRecord
  belongs_to :person_info
   


  
end

app/models/person_info.rb
class PersonInfo < ApplicationRecord
	has_many :person_experiences,  :dependent => :destroy
	 accepts_nested_attributes_for :person_experiences
	 validates_associated :person_experiences

mount_uploader :cv_upload, CvUploadUploader
	  # validate :validate_experience

	 validates :cnic, numericality: true
	  validates :age, numericality: { greater_than: 10 }
	   validates :mobile, numericality: { greater_than: 10 }
	   validates :cnic, presence: { greater_than: 10 }
	     validates :mobile, uniqueness: true
	     

	   validates :name, presence: true
	   validates :age, presence: true
	   validates :gender, presence: true
	   validates :address, presence: true
	   validates :mobile, presence: true

	   validates :apply_for, presence: true
	   validates :area, presence: true
	   validates :detail_area_research, presence: true
	   validates :cv_upload, presence: true
		
	   def validate_experience
	   end   
  	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/person_infos_controller.rb
class PersonInfosController < ApplicationController
  before_action :set_person_info, only: [:show, :edit, :update, :destroy]

  # GET /person_infos
  # GET /person_infos.json
  def index
    @person_infos = PersonInfo.all
  end

  # GET /person_infos/1
  # GET /person_infos/1.json
  def show
  end

  # GET /person_infos/new
  def new
    @person_info = PersonInfo.new
  
    # @person_info.person_experiences.build
  end

  # GET /person_infos/1/edit
  def edit
  end

  # POST /person_infos
  # POST /person_infos.json
  def create
    @person_info = PersonInfo.new(person_info_params)

     @person_experience = params[:person_info][:person_experiences]
     
      # if @person_experience.length >2 
        respond_to do |format|
          if @person_info.save
            @person_experience.each do |person|
              unless person.blank?
                @person = PersonExperience.create(experience_name: person, person_info_id: @person_info.id)
              end
            end
            format.html { redirect_to @person_info, notice: 'Person info was successfully created.' }
            format.json { render :show, status: :created, location: @person_info }
          else
            format.html { render :new }
            format.json { render json: @person_info.errors, status: :unprocessable_entity }
          end
        end
      # else
      #   flash[:notice] = 'Sorry please select experience more then one'
  
        
      # end
  end

  # PATCH/PUT /person_infos/1
  # PATCH/PUT /person_infos/1.json
  def update
    respond_to do |format|
       @person_experience = params[:person_info][:person_experiences]
       @person_experiences.destroy_all
     
      if @person_info.update(person_info_params)
        @person_experience.each do |person|
          unless person.blank?
            @person = PersonExperience.create(experience_name: person, person_info_id: @person_info.id)
          end
        end
        format.html { redirect_to @person_info, notice: 'Person info was successfully updated.' }
        format.json { render :show, status: :ok, location: @person_info }
      else
        format.html { render :edit }
        format.json { render json: @person_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /person_infos/1
  # DELETE /person_infos/1.json
  def destroy
    @person_info.destroy
    respond_to do |format|
      format.html { redirect_to person_infos_url, notice: 'Person info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_person_info
      @person_info = PersonInfo.find(params[:id])
      @person_experiences = @person_info.person_experiences

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_info_params
      aaa = params[:person_info][:person_experiences].reject { |c| c.empty? }
      params.require(:person_info).permit(:name, :cnic, :age, :gender, :address, :mobile, :apply_for, :area, :detail_area_research, :cv_upload,:aaa)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/person_infos_helper.rb
module PersonInfosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oaf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/person_infos/_form.html.erb
<%= simple_form_for@person_info , :html => { multipart: true } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :cnic %>
    <%= f.input :age %>
     <%= f.input :gender, as: :radio_buttons, collection: [['0', 'female'], ['1', 'male']], label_method: :second, value_method: :first %>
    <%= f.input :address %>
    <%= f.input :mobile %>
    <%= f.input :apply_for %>
    <%= f.input :area %>
    <%= f.input :detail_area_research %>
    <%= f.input :person_experiences, collection: ['Designed interview questions ','Conducted qualitative interviews','Analysed qualitative interviews','Reported qualitative research','Published qualitative research'],as: :check_boxes ,:checked => @person_experiences.present? ? @person_experiences.pluck(:experience_name) : []
%>
 
    <%= f.input :cv_upload,as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/person_infos/edit.html.erb
<h1>Editing Person Info</h1>

<%= render 'form', person_info: @person_info %>

<%= link_to 'Show', @person_info %> |
<%= link_to 'Back', person_infos_path %>

app/views/person_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Person Infos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cnic</th>
      <th>Age</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Address</th>
      <th>Mobile</th>
      <th>Apply for</th>
      <th>Area</th>
      <th>Detail area research</th>
      <th>Cv upload</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @person_infos.each do |person_info| %>
      <tr>
        <td><%= person_info.name %></td>
        <td><%= person_info.cnic %></td>
        <td><%= person_info.age %></td>
        <td><%= person_info.age %></td>
        <td><%= person_info.gender %></td>
        <td><%= person_info.address %></td>
        <td><%= person_info.mobile %></td>
        <td><%= person_info.apply_for %></td>
        <td><%= person_info.area %></td>
        <td><%= person_info.detail_area_research %></td>
        <td>
           <%= image_tag(person_info.cv_upload.url, size: "300x300") if person_info.cv_upload?  %>
        </td>
        <td><%= link_to 'Show', person_info %></td>
        <td><%= link_to 'Edit', edit_person_info_path(person_info) %></td>
        <td><%= link_to 'Destroy', person_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person Info', new_person_info_path %>

app/views/person_infos/new.html.erb
<h1>New Person Info</h1>

<%= render 'form', person_info: @person_info %>

<%= link_to 'Back', person_infos_path %>

app/views/person_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person_info.name %>
</p>

<p>
  <strong>Cnic:</strong>
  <%= @person_info.cnic %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person_info.age %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person_info.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @person_info.gender %>
</p>

<p>
  <strong>Address:</strong>
  <%= @person_info.address %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @person_info.mobile %>
</p>

<p>
  <strong>Apply for:</strong>
  <%= @person_info.apply_for %>
</p>

<p>
  <strong>Area:</strong>
  <%= @person_info.area %>
</p>

<p>
  <strong>Detail area research:</strong>
  <%= @person_info.detail_area_research %>
</p>

<p>
  <strong>Cv upload:</strong>

  <%= image_tag(@person_info.cv_upload.url, size: "300x300")  %>
</p>

<%= link_to 'Edit', edit_person_info_path(@person_info) %> |
<%= link_to 'Back', person_infos_path %>